// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ercqioeatutdhvdgceoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyY3Fpb2VhdHV0ZGh2ZGdjZW96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3OTA5MjQsImV4cCI6MjA1OTM2NjkyNH0.lFdqphKTXWbh-CpHkm7pawrg9MYggKbyhFPHZmPlTRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);